### ISSUE TITLE
Unable to deploy via 'complete-deployment'

### ISSUE THREAD

**Issue by elrob** [agoravoting/agora-dev-box#11]
https://github.com/agoravoting/agora-dev-box/blob/master/doc/complete-deployment.md

I was able to reach [Agora server part 1](https://github.com/agoravoting/agora-dev-box/blob/master/doc/complete-deployment.md#agora-server-part-1)

After copying the ymls, I have run `vagrant provision`

I first had problems with the [*AgoraElections, restarting supervisor* task](https://github.com/agoravoting/agora-dev-box/blob/master/agora-elections/main.yml#L83) but after adjusting the sleep time it worked. 

Then got stuck at the [*AgoraCoreView, building* task](https://github.com/agoravoting/agora-dev-box/blob/master/agora-core-view/app.yml#L20). It kept failing saying that build.sh could not be found.
However, I then ssh'd in to the box and executed the build.sh manually.
I then commented out the *AgoraCoreView, building* task and tried again but it then broke on a later task.

I think the provisioning needs checking. Either the guide is outdated or perhaps the provisioning steps.

I'd appreciate some assistance in getting up and running...

**Comment by edulix** [comment]
have you tried to use the branch next of the repos?

**Comment by christophwong** [comment]
We retried it on the *next* branch on a different machine from scratch and ran into the same error at *AgoraCoreView, building task*


![screen shot 2015-05-27 at 10 54 37](https://cloud.githubusercontent.com/assets/3989823/7833492/31285296-045f-11e5-94ae-75697cbfa155.png)

```
TASK: [AgoraCoreView,  Creating build.sh] *************************************
changed: [default] => {"changed": true, "checksum": "a7a2400f570a889a6ee7a20844e57e9250f839f3", "dest": "/home/agoracore/agora-core-view/build.sh", "gid": 1005, "group": "agoracore", "md5sum": "2862713f8c8ea9486c79056fa41039de", "mode": "0744", "owner": "agoracore", "size": 47, "src": "/home/vagrant/.ansible/tmp/ansible-tmp-1432720444.33-81490904347378/source", "state": "file", "uid": 1005}

TASK: [AgoraCoreView, creating dist dir] **************************************
changed: [default] => {"changed": true, "gid": 1005, "group": "agoracore", "mode": "0755", "owner": "agoracore", "path": "/home/agoracore/dist", "size": 4096, "state": "directory", "uid": 1005}

TASK: [AgoraCoreView, building] ***********************************************
failed: [default] => {"changed": true, "cmd": "build.sh", "delta": "0:00:00.001445", "end": "2015-05-27 09:52:33.445924", "rc": 127, "start": "2015-05-27 09:52:33.444479", "warnings": []}
stderr: /bin/sh: 1: build.sh: not found

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/chwong/playbook.retry

default                    : ok=90   changed=79   unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by danigm** [comment]
There was an error in the ansible script. I've fixed it and now this should work. Try again with the agora-dev-box next branch.

https://github.com/agoravoting/agora-dev-box/commit/12aae4582a64b4d0e7cfceb1c791453446fa4985

**Comment by christophwong** [comment]
The fix has got me passed the build task but there is still an error at *All in one nginx* task.
I've tried re-running provision again, and also reordering this task with the *DNIE and FNMT ca task* but I did not understand what the task is meant to be achieving and not sure how to work around it.


This is the console output:
```
TASK: [All in one nginx] ******************************************************
fatal: [default] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'dnie_host'", 'failed': True}
fatal: [default] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'dnie_host'", 'failed': True}

FATAL: all hosts have already failed -- aborting
```

**Comment by danigm** [comment]
That's my fault, I broke it... But now I've fixed it. Try the last agora-dev-box update. The DNIE and FNMT is configuration for client side authentication with spanish goverment certificates, but it isn't completed. So it's not usable yet and I disabled it by default if it's not set in the configuration, that is the tutorial case.
